spring:
  application:
    name: studyBotBackend

  datasource:
    url: jdbc:mysql://localhost:3306/server
    username: root
    password: JUHUEu21uhduiHDDSie92UIJIOr39fsd9asdkJS
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true



server:
  port: 8000
debug: false
