spring:
  application:
    name: studyBotBackend

  datasource:
    url: jdbc:mysql://localhost:3306/server
    username: root
    password: JUHUEu21uhduiHDDSie92UIJIOr39fsd9asdkJS
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  access-token-expiration-time: 86400999
  refresh-token-expiration-time: 432000999
  bot-token-expiration-time: 2592000999
logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG

server:
  port: 8000
debug: false
